// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PedagioPayPortalUsuario.Models
{
    [Table("CONCESSAO")]
    public partial class CONCESSAO
    {
        [Key]
        public byte ID_CONCESSAO { get; set; }
        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string RAZAO_SOCIAL { get; set; }
        [Required]
        [StringLength(30)]
        [Unicode(false)]
        public string NM_BREVE { get; set; }
        [Required]
        [StringLength(25)]
        [Unicode(false)]
        public string CNPJ { get; set; }
        public Guid TOKEN { get; set; }
        public short ID_GRUPO { get; set; }
        public int? TERMINAL_ID { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string CONCESSIONARIA_ID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string LOGO { get; set; }
        public bool? CD_STATUS { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DH_TIMESTAMP { get; set; }
    }
}