using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace PedagioPayPortalUsuario.Models
{
        // <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
        [Table("DEBITO")]
        public partial class DEBITO
        {
            [Key]
            public int ID_DEBITO { get; set; }
            [StringLength(500)]
            [Unicode(false)]
            public string TOKEN_USUARIO { get; set; }
            [Required]
            public long ID_PASSAGEM { get; set; }
            [Required]
            [StringLength(20)]
            [Unicode(false)]
            public string CATEGORIA { get; set; }
            [Required]
            public int EIXOS { get; set; }
            [Required]
            [Column(TypeName = "smallmoney")]
            [Unicode(false)]
            public decimal VALOR { get; set; }
            [Required]
            public string VENCIMENTO { get; set; }
            [Column(TypeName = "datetime")]
            public DateTime? PAGO_EM {  get; set; }
            public string CNPJ {  get; set; }
            public string PORTICO { get; set; } 
            [Required]
            public DateTime DH_PASSAGEM { get; set; }
            [Required]
            public string CONCESSAO { get; set; }
            [StringLength(7)]
            [Unicode(false)]
            public string PLACA { get; set; }
            [StringLength(10)]
            [Unicode(false)]
            public string TAG { get; set; }
            public byte? ID_OSA { get; set; }
            public bool? CD_STATUS { get; set; }
            [Column(TypeName = "datetime")]
            public DateTime? DH_TIMESTAMP { get; set; }
        }
    }

