// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PedagioPayPortalUsuario.Models
{
    [Table("PASSAGEM")]
    public partial class PASSAGEM
    {
        [Key]
        public long ID_PASSAGEM { get; set; }
        [Key]
        [StringLength(50)]
        [Unicode(false)]
        public string ID_TRANSITO { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string COB { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string DAC { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string VAL { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string CATEGORIA { get; set; }
        [Column(TypeName = "smallmoney")]
        public decimal VALOR { get; set; }
        public int? ID_STATUS { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DH_ATUALIZACAO_STATUS { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DH_PASSAGEM { get; set; }
        public short ID_CONCESSAO { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string ID_PRACA_PORTICO { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string PISTA_FAIXA { get; set; }
        public int? QTD_ATUALIZACAO_PASSAGEM { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string NOME_SENTIDO { get; set; }
        [StringLength(30)]
        [Unicode(false)]
        public string ID_MOTIVO_COBRANCA { get; set; }
        [StringLength(7)]
        [Unicode(false)]
        public string PLACA { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string TAG { get; set; }
        public byte? ID_OSA { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string COD_CUPOM { get; set; }
        public int? EIXOS_VAL { get; set; }
        public bool? BANDA_DUPLA { get; set; }
        public bool? CD_STATUS { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DH_TIMESTAMP { get; set; }
    }
}