// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace PedagioPayPortalUsuario.Models
{
    public partial class PEDAGIOPAYContext : DbContext
    {
        public PEDAGIOPAYContext()
        {
        }

        public PEDAGIOPAYContext(DbContextOptions<PEDAGIOPAYContext> options)
            : base(options)
        {
        }

        public virtual DbSet<CONCESSAO> CONCESSAOs { get; set; }
        public virtual DbSet<PASSAGEM> PASSAGEMs { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
        public virtual DbSet<PLACAs> PLACAs { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CONCESSAO>(entity =>
            {
                entity.Property(e => e.ID_CONCESSAO).ValueGeneratedOnAdd();

                entity.Property(e => e.CD_STATUS).HasDefaultValueSql("((1))");

                entity.Property(e => e.DH_TIMESTAMP).HasDefaultValueSql("(getdate())");
            });

            modelBuilder.Entity<PASSAGEM>(entity =>
            {
                entity.HasKey(e => new { e.ID_PASSAGEM, e.ID_TRANSITO })
                    .HasName("PK_PASSAGEM_TRANSITO");

                entity.HasIndex(e => e.ID_TRANSITO, "IX_TRANSITO")
                    .IsUnique()
                    .HasFillFactor(90);

                entity.Property(e => e.ID_PASSAGEM).ValueGeneratedOnAdd();

                entity.Property(e => e.CD_STATUS).HasDefaultValueSql("((1))");

                entity.Property(e => e.DH_TIMESTAMP).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.PLACA).IsFixedLength();

                entity.Property(e => e.TAG).IsFixedLength();
            });

            modelBuilder.Entity<USUARIO>(entity =>
            {
                entity.HasKey(e => e.ID_USUARIO)
                    .HasName("PK_USUARIO_1");

                entity.Property(e => e.BL_VALIDADO).HasDefaultValueSql("((0))");

                entity.Property(e => e.CD_STATUS).HasDefaultValueSql("((1))");

                entity.Property(e => e.CODIGO_VALIDACAO).IsFixedLength();

                entity.Property(e => e.DH_TIMESTAMP).HasDefaultValueSql("(getdate())");
            });

            modelBuilder.Entity<PLACAs>(entity =>
            {
                entity.HasKey(e => e.ID_USUARIO_PLACA)
                    .HasName("PK_CONSULTA");

                entity.HasIndex(e => new { e.TOKEN_USUARIO, e.PLACA }, "IX_USUARIO_PLACA")
                    .IsUnique()
                    .HasFillFactor(90);

                entity.Property(e => e.CD_STATUS).HasDefaultValueSql("((1))");

                entity.Property(e => e.DH_TIMESTAMP).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.PLACA).IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}