// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PedagioPayPortalUsuario.Models
{
    [Table("USUARIO")]
    [Index("CPF_CNPJ", Name = "IX_CPF_CNPJ", IsUnique = true)]
    [Index("EMAIL", Name = "IX_EMAIL", IsUnique = true)]
    public partial class USUARIO
    {
        [Key]
        public int ID_USUARIO { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string NOME { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string EMAIL { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string CPF_CNPJ { get; set; }
        [StringLength(12)]
        [Unicode(false)]
        public string CELULAR { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string SENHA { get; set; }
        public bool? BL_VALIDADO { get; set; }
        [StringLength(4)]
        [Unicode(false)]
        public string CODIGO_VALIDACAO { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string TOKEN { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ID_FACEBOOK { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ID_GOOGLE { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ID_APPLE { get; set; }
        public bool? CD_STATUS { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DH_TIMESTAMP { get; set; }
    }
}