// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PedagioPayPortalUsuario.Models;

#nullable disable

namespace PedagioPayPortalUsuario.Migrations
{
    [DbContext(typeof(PEDAGIOPAYContext))]
    partial class PEDAGIOPAYContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<short>("SQ_PEDIDO_MERCHANT_ORDER_ID")
                .HasMin(1L)
                .HasMax(9999L)
                .IsCyclic();

            modelBuilder.Entity("PedagioPayPortalUsuario.Models.CONCESSAO", b =>
                {
                    b.Property<byte>("ID_CONCESSAO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("ID_CONCESSAO"));

                    b.Property<bool?>("CD_STATUS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime?>("DH_TIMESTAMP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<short>("ID_GRUPO")
                        .HasColumnType("smallint");

                    b.Property<string>("NM_BREVE")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("RAZAO_SOCIAL")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("TOKEN")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID_CONCESSAO");

                    b.ToTable("CONCESSAO");
                });

            modelBuilder.Entity("PedagioPayPortalUsuario.Models.DEBITO", b =>
                {
                    b.Property<int>("ID_DEBITO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_DEBITO"));

                    b.Property<string>("CATEGORIA")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("CD_STATUS")
                        .HasColumnType("bit");

                    b.Property<string>("CONCESSAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DH_PASSAGEM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DH_TIMESTAMP")
                        .HasColumnType("datetime");

                    b.Property<int>("EIXOS")
                        .HasColumnType("int");

                    b.Property<byte?>("ID_OSA")
                        .HasColumnType("tinyint");

                    b.Property<long>("ID_PASSAGEM")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PAGO_EM")
                        .HasColumnType("datetime");

                    b.Property<string>("PLACA")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("TAG")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TOKEN_USUARIO")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("VALOR")
                        .IsUnicode(false)
                        .HasColumnType("smallmoney");

                    b.Property<string>("VENCIMENTO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_DEBITO");

                    b.ToTable("DEBITO");
                });

            modelBuilder.Entity("PedagioPayPortalUsuario.Models.PASSAGEM", b =>
                {
                    b.Property<long>("ID_PASSAGEM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_PASSAGEM"));

                    b.Property<string>("ID_TRANSITO")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CATEGORIA")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("CD_STATUS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("COB")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("COD_CUPOM")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DAC")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DH_PASSAGEM")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DH_TIMESTAMP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<short>("ID_CONCESSAO")
                        .HasColumnType("smallint");

                    b.Property<string>("ID_MOTIVO_COBRANCA")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<byte?>("ID_OSA")
                        .HasColumnType("tinyint");

                    b.Property<string>("ID_PRACA_PORTICO")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("ID_STATUS")
                        .HasColumnType("int");

                    b.Property<string>("NOME_SENTIDO")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PISTA_FAIXA")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PLACA")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("char(7)")
                        .IsFixedLength();

                    b.Property<int?>("QTD_ATUALIZACAO_PASSAGEM")
                        .HasColumnType("int");

                    b.Property<string>("TAG")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("VAL")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("VALOR")
                        .HasColumnType("smallmoney");

                    b.HasKey("ID_PASSAGEM", "ID_TRANSITO")
                        .HasName("PK_PASSAGEM_TRANSITO");

                    b.ToTable("PASSAGEM");
                });

            modelBuilder.Entity("PedagioPayPortalUsuario.Models.PLACAS", b =>
                {
                    b.Property<int>("ID_USUARIO_PLACA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_USUARIO_PLACA"));

                    b.Property<int?>("ANO")
                        .HasColumnType("int");

                    b.Property<bool?>("CD_STATUS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("COR")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("DH_TIMESTAMP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MARCA")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("MODELO")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("PLACA")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("char(7)")
                        .IsFixedLength();

                    b.Property<string>("TOKEN_USUARIO")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("USUARIO_EMAIL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_USUARIO_PLACA")
                        .HasName("PK_CONSULTA");

                    b.ToTable("USUARIO_PLACA");
                });

            modelBuilder.Entity("PedagioPayPortalUsuario.Models.USUARIO", b =>
                {
                    b.Property<string>("EMAIL")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("BL_VALIDADO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("CD_STATUS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("CELULAR")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("CODIGO_VALIDACAO")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("char(4)")
                        .IsFixedLength();

                    b.Property<string>("CPF_CNPJ")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("DH_TIMESTAMP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ID_APPLE")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ID_FACEBOOK")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ID_GOOGLE")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ID_USUARIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_USUARIO"));

                    b.Property<string>("NOME")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SENHA")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TOKEN")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("EMAIL");

                    b.ToTable("USUARIO");
                });
#pragma warning restore 612, 618
        }
    }
}
